# Generated by Django 5.1.6 on 2025-03-08 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('size', models.CharField(default='原版', max_length=15)),
                ('color', models.CharField(default='原色', max_length=15)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('on_road', models.IntegerField(default=0)),
                ('in_stock', models.IntegerField(default=0)),
                ('been_order', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', related_query_name='inventories', to='brand.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', related_query_name='inventories', to='category.category')),
            ],
        ),
    ]
