# Generated by Django 5.1.6 on 2025-03-09 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchase_purchasedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
