# Generated by Django 5.1.6 on 2025-03-13 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_receive_receivedetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_logs', related_query_name='purchase_logs', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', related_query_name='logs', to='inventory.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_logs', related_query_name='receive_logs', to=settings.AUTH_USER_MODEL)),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', related_query_name='logs', to='inventory.receive')),
            ],
        ),
    ]
