# Generated by Django 5.1.6 on 2025-03-11 12:24

import django.db.models.deletion
import django.utils.timezone
import shortuuidfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='客户姓名')),
                ('telephone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(max_length=200, verbose_name='详细住址')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('level', models.IntegerField(choices=[(0, '已成交'), (1, '一级客户'), (2, '二级客户'), (3, '三级客户'), (4, '四级客户'), (5, '已流失')], default=1, verbose_name='客户级别')),
                ('last_follow_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最近一次跟进时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='所属员工')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['level', 'last_follow_time'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpRecord',
            fields=[
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='跟进信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_records', to='client.client', verbose_name='跟进客户')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_records', to=settings.AUTH_USER_MODEL, verbose_name='跟进员工')),
            ],
            options={
                'verbose_name': '跟进记录',
                'verbose_name_plural': '跟进记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
