# Generated by Django 5.1.6 on 2025-03-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='联系电话'),
        ),
    ]
