# Generated by Django 5.1.6 on 2025-03-12 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('inventory', '0004_receive_receivedetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('telephone', models.CharField(max_length=20, verbose_name='联系电话')),
            ],
            options={
                'verbose_name': '安装人员',
                'verbose_name_plural': '安装人员',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='订单编号')),
                ('sign_time', models.DateTimeField(auto_now_add=True, verbose_name='签单时间')),
                ('last_operation_time', models.DateTimeField(auto_now=True, verbose_name='最后一次操作时间')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总额')),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='首付定金')),
                ('received_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已收尾款')),
                ('pending_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='待收尾款')),
                ('delivery_status', models.IntegerField(choices=[(1, '新订单'), (2, '已送货')], default=1, verbose_name='订单送货状态')),
                ('payment_status', models.IntegerField(choices=[(1, '未结清'), (2, '已结清')], default=1, verbose_name='订单结清状态')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成本总价')),
                ('installation_time', models.DateTimeField(blank=True, null=True, verbose_name='安装时间')),
                ('installation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='安装费用')),
                ('transportation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运输费用')),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='毛利润')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='client.client', verbose_name='客户信息')),
                ('installer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.installer', verbose_name='安装人员')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='签单人员')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-sign_time'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.TextField(verbose_name='操作说明')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人员')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='order.order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BalancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='本次收款')),
                ('payment_time', models.DateTimeField(auto_now_add=True, verbose_name='收款时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_payments', to=settings.AUTH_USER_MODEL, verbose_name='操作人员')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_payments', to='order.order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '尾款收取',
                'verbose_name_plural': '尾款收取',
                'ordering': ['-payment_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='订购数量')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='inventory.inventory', verbose_name='订购商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='order.order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
            },
        ),
    ]
