# Generated by Django 5.1.6 on 2025-03-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='测试', max_length=200, verbose_name='安装地址'),
            preserve_default=False,
        ),
    ]
