# Generated by Django 5.1.6 on 2025-03-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installer',
            name='telephone',
            field=models.CharField(max_length=20, unique=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.IntegerField(choices=[(1, '新订单'), (2, '已送货'), (3, '已作废')], default=1, verbose_name='订单送货状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(1, '未结清'), (2, '已结清'), (3, '已作废')], default=1, verbose_name='订单结清状态'),
        ),
    ]
